#ifndef __CONSTANTS__
#define __CONSTANTS__

static int COLLECTING_WORKERS_COMMITTEES=0;
static int COLLECTING_WORKERS_PER_COMMITTEE=0;
static int SPLITTING_WORKERS_COMMITTEES=0;
static int SPLITTING_WORKERS_PER_COMMITTEE=0;
static int DISTRIBUTING_WORKERS_COMMITTEES=0;
static int DISTRIBUTING_WORKERS_PER_COMMITTEE=0;
static int CARGO_PLANES=0;
static int WHEAT_MIN_PER_PLANE=0;
static int WHEAT_MAX_PER_PLANE=0;
static int WHEAT_CONTAINER_MASS=0;
static int MIN_PLANE_HEIGHT=0;
static int MAX_PLANE_HEIGHT=0;
static int HEIGHT_THRESHOLD=0;
static int REFILL_PERIOD_MIN=0;
static int REFILL_PERIOD_MAX=0;
static int COLLECTING_WORKERS_ENERGY_LEVEL_MIN=0;
static int COLLECTING_WORKERS_ENERGY_LEVEL_MAX=0;
static int COLLECTING_WORKER_TIRING_LEVEL=0;
static int REPLACE_COLLECTING_WORKER_THRESHOLD=0;
static int NUM_OF_FAMILIES=0;
static int DISTRIBUTION_COMMITTIEE_CARRY_BAGS=0;
static int STARVATION_RATE_MIN=0;
static int STARVATION_RATE_MAX=0;
static int REPLACE_DISTRIBUTING_WORKER_THRESHOLD=0;
static int STARVATION_LEVEL_INCREASE_PER_MIN=0;
static int STARVATION_LEVEL_DROP_PER_BAG=0;
static int STARVATION_LEVEL_PASS_AWAY_THRESHOLD=0;
static int APP_LENGTH_SECONDS=0;
static int CARGO_PLANES_CRASHED_THRESHOLD=0;
static int LOST_CARGO_CONTAINERS_THRESHOLD=0;
static int COLLECTING_WORKERS_MARTYRS_THRESHOLD=0;
static int DISTRIBUTION_WORKERS_MARTYRS_THRESHOLD=0;
static int FAMILIES_PASS_AWAY_THRESHOLD=0;
static int TIME_NEEDED_TO_DROP_CONTAINERS_MIN=0;
static int TIME_NEEDED_TO_DROP_CONTAINERS_MAX=0;
static int TIME_BETWEEN_TWO_PLANES=0;
static int TIME_NEEDED_TO_COLLECT_CONTAINERS_MIN=0;
static int TIME_NEEDED_TO_COLLECT_CONTAINERS_MAX=0;

#endif